# Generated by Django 2.0.3 on 2018-04-12 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('divisor', models.DecimalField(decimal_places=25, max_digits=50)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('price_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('price_percent_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('market_cap', models.DecimalField(decimal_places=25, max_digits=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('divisor', models.DecimalField(decimal_places=25, max_digits=50)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdex.Index')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='indices',
            field=models.ManyToManyField(to='altdex.Index'),
        ),
    ]
