# Generated by Django 2.0.3 on 2018-05-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='api',
            field=models.CharField(default='CryptoCompare', max_length=25),
        ),
    ]
