# Generated by Django 2.0.3 on 2018-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0002_coin_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_marketcap_id',
            field=models.IntegerField(default=0, max_length=4),
        ),
    ]
