# Generated by Django 2.0.3 on 2018-05-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0003_coin_coin_marketcap_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexprice',
            name='price_change',
        ),
        migrations.AlterField(
            model_name='coin',
            name='coin_marketcap_id',
            field=models.IntegerField(default=0),
        ),
    ]
