# Generated by Django 2.0.5 on 2018-05-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0004_auto_20180505_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexprice',
            name='change_24h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
            preserve_default=False,
        ),
    ]
