# Generated by Django 2.0.5 on 2018-06-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0006_auto_20180518_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
