# Generated by Django 2.0.5 on 2018-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0007_auto_20180601_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='website',
            field=models.CharField(default='', max_length=50),
        ),
    ]
