# Generated by Django 2.0.5 on 2018-10-13 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('altdex', '0008_coin_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_high', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('day_low', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('price_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('rs_14', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('rsi_14', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('sma_12', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('sma_26', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('ema_12', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('ema_26', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('macd', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('macd_trend', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('fib', models.DecimalField(decimal_places=10, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdex.Index')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
    ]
