# Generated by Django 2.0.3 on 2018-03-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CoinCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('price_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('price_percent_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('volume', models.DecimalField(decimal_places=25, max_digits=50)),
                ('market_cap', models.DecimalField(decimal_places=25, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdexapp.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='CoinDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=50, max_digits=50)),
                ('high', models.DecimalField(decimal_places=50, max_digits=50)),
                ('low', models.DecimalField(decimal_places=50, max_digits=50)),
                ('day', models.DateField(blank=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdexapp.Coin')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('divisor', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='IndexCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('price_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('price_percent_change', models.DecimalField(decimal_places=25, max_digits=50)),
                ('volume', models.DecimalField(decimal_places=25, max_digits=50)),
                ('market_cap', models.DecimalField(decimal_places=25, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdexapp.Index')),
            ],
        ),
        migrations.CreateModel(
            name='IndexDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.DecimalField(decimal_places=50, max_digits=50)),
                ('high', models.DecimalField(decimal_places=50, max_digits=50)),
                ('low', models.DecimalField(decimal_places=50, max_digits=50)),
                ('day', models.DateField(blank=True)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='altdexapp.Index')),
            ],
        ),
        migrations.AddField(
            model_name='coin',
            name='indices',
            field=models.ManyToManyField(to='altdexapp.Index'),
        ),
    ]
